name: Deploy Node.js to Heroku

on:
  push:
    branches:
      - main  # Set this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'  # Set this to the node version you are using

    - name: Install dependencies
      run: npm install

    # Uncomment the following two lines if your project has a build step
    - name: Build
      run: npm run build

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12  # This GitHub Action simplifies the deployment to Heroku
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "ecommerce-dashboard" 
        heroku_email: "lakotacamp3@gmail.com"
